main:
  push:
    - services:
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      docker:
        image: docker:27-cli
        volumes:
          - /root/.docker/buildx-cache:${CNB_WORKSPACE}/.cache/buildx
      stages:
        - name: publish architecture images
          script: sh scripts/cnb-publish-images.sh

$:
  tag_push:
    - services:
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      docker:
        image: docker:27-cli
        volumes:
          - /root/.docker/buildx-cache:${CNB_WORKSPACE}/.cache/buildx
      stages:
        - name: publish release architecture images
          script: sh scripts/cnb-publish-images.sh
