main:
  push:
    - services:
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      docker:
        image: docker:27-cli
        volumes:
          - type: cache
            source: buildx_cache  # 缓存卷名称（自定义）
            target: /.cache/buildx  # 容器内目标路径
      stages:
        - name: publish architecture images
          script: sh scripts/cnb-publish-images.sh

$:
  tag_push:
    - services:
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      docker:
        image: docker:27-cli
        volumes:
          - type: cache
            source: buildx_cache  # 缓存卷名称（自定义）
            target: /.cache/buildx  # 容器内目标路径
      stages:
        - name: publish release architecture images
          script: sh scripts/cnb-publish-images.sh
