main:
  push:
    - name: "push-main-job"
      runner:
        tags: cnb:arch:amd64
      services:
        - name: "docker"
          options:
            rootlessBuildkitd:
              enabled: true
      docker:
        image: "docker:27-cli"
        volumes:
          - "/root/.cache/buildx"
      stages:
        - name: "publish architecture images"
          script: "sh scripts/cnb-publish-images.sh"

$:
  tag_push:
    - name: "tag-push-job"
      runner:
        tags: cnb:arch:amd64
      services:
        - name: "docker"
          options:
            rootlessBuildkitd:
              enabled: true
      docker:
        image: "docker:27-cli"
        volumes:
          - "/root/.cache/buildx"
      stages:
        - name: "publish release architecture images"
          script: "sh scripts/cnb-publish-images.sh"
